project_id = "ntiswktkeudikydbacry"

[auth.email]
enable_confirmations = false

[functions.chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.tts]
verify_jwt = false

[functions.stt]
verify_jwt = false
